tcp:
  - name: LocalPythonServer
    host: 127.0.0.1:8001

settings:
  pid: /tmp/easeprobe.pid
  name: MyService
  timeformat: "2001-01-01 00:00:00"
  probe:
    timeout: 2s
    interval: 15s
    failure: 1
    success: 1
